# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/7f42ksnx9chv8clzni5k3ym0dp5sk3xq-cmake-4.1.1/bin/cmake

# The command to remove a file.
RM = /nix/store/7f42ksnx9chv8clzni5k3ym0dp5sk3xq-cmake-4.1.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wyattgill/Github/poe_overlay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wyattgill/Github/poe_overlay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/7f42ksnx9chv8clzni5k3ym0dp5sk3xq-cmake-4.1.1/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/7f42ksnx9chv8clzni5k3ym0dp5sk3xq-cmake-4.1.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wyattgill/Github/poe_overlay/CMakeFiles /Users/wyattgill/Github/poe_overlay//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wyattgill/Github/poe_overlay/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wyattgill/Github/poe_overlay/CMakeFiles /Users/wyattgill/Github/poe_overlay//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wyattgill/Github/poe_overlay/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named poe_overlay

# Build rule for target.
poe_overlay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poe_overlay
.PHONY : poe_overlay

# fast build rule for target.
poe_overlay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/build
.PHONY : poe_overlay/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

app/main.o: app/main.cpp.o
.PHONY : app/main.o

# target to build an object file
app/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.o
.PHONY : app/main.cpp.o

app/main.i: app/main.cpp.i
.PHONY : app/main.i

# target to preprocess a source file
app/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.i
.PHONY : app/main.cpp.i

app/main.s: app/main.cpp.s
.PHONY : app/main.s

# target to generate assembly for a file
app/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.s
.PHONY : app/main.cpp.s

src/passive_tree.o: src/passive_tree.cpp.o
.PHONY : src/passive_tree.o

# target to build an object file
src/passive_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/passive_tree.cpp.o
.PHONY : src/passive_tree.cpp.o

src/passive_tree.i: src/passive_tree.cpp.i
.PHONY : src/passive_tree.i

# target to preprocess a source file
src/passive_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/passive_tree.cpp.i
.PHONY : src/passive_tree.cpp.i

src/passive_tree.s: src/passive_tree.cpp.s
.PHONY : src/passive_tree.s

# target to generate assembly for a file
src/passive_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/passive_tree.cpp.s
.PHONY : src/passive_tree.cpp.s

src/poe2_client.o: src/poe2_client.cpp.o
.PHONY : src/poe2_client.o

# target to build an object file
src/poe2_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/poe2_client.cpp.o
.PHONY : src/poe2_client.cpp.o

src/poe2_client.i: src/poe2_client.cpp.i
.PHONY : src/poe2_client.i

# target to preprocess a source file
src/poe2_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/poe2_client.cpp.i
.PHONY : src/poe2_client.cpp.i

src/poe2_client.s: src/poe2_client.cpp.s
.PHONY : src/poe2_client.s

# target to generate assembly for a file
src/poe2_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/poe2_client.cpp.s
.PHONY : src/poe2_client.cpp.s

src/poe_logger.o: src/poe_logger.cpp.o
.PHONY : src/poe_logger.o

# target to build an object file
src/poe_logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/poe_logger.cpp.o
.PHONY : src/poe_logger.cpp.o

src/poe_logger.i: src/poe_logger.cpp.i
.PHONY : src/poe_logger.i

# target to preprocess a source file
src/poe_logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/poe_logger.cpp.i
.PHONY : src/poe_logger.cpp.i

src/poe_logger.s: src/poe_logger.cpp.s
.PHONY : src/poe_logger.s

# target to generate assembly for a file
src/poe_logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poe_overlay.dir/build.make CMakeFiles/poe_overlay.dir/src/poe_logger.cpp.s
.PHONY : src/poe_logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... poe_overlay"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... src/passive_tree.o"
	@echo "... src/passive_tree.i"
	@echo "... src/passive_tree.s"
	@echo "... src/poe2_client.o"
	@echo "... src/poe2_client.i"
	@echo "... src/poe2_client.s"
	@echo "... src/poe_logger.o"
	@echo "... src/poe_logger.i"
	@echo "... src/poe_logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

